name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build, Test, and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: '15.x'

            # Install modules
            - name: Install modules
              run: npm install

            # Run tests
            - name: Run Jest tests
              run: npm run test

            # Build App
            - name: Build React App
              run: npm run build

            # Push to Separate Branch for Pages
            #- name: Push git subdirectory as branch
            #  uses: s0/git-publish-subdir-action@v2.4.0
            #  env:
            #      REPO: self
            #      BRANCH: gh-pages
            #      FOLDER: build
            #      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Docker Build & Push to GitHub Package
              uses: opspresso/action-docker@v0.2.17
              with:
                args: --docker
              env:
                USERNAME: yupiel
                PASSWORD: ${{ secrets.GITHUB_TOKEN }}
                REGISTRY: docker.pkg.github.com
                DOCKERFILE: Dockerfile
                IMAGE_NAME: helth_frontend
                TAG_NAME: latest
                LATEST: true